# Generated by Django 4.1.7 on 2023-03-19 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_band_year_formed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('type', models.CharField(choices=[('RC', 'Records'), ('CL', 'Clothing'), ('PT', 'Posters'), ('MC', 'Miscellaneous')], max_length=50)),
            ],
        ),
    ]
