# Generated by Django 4.1.7 on 2023-03-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default='color', max_length=20),
            preserve_default=False,
        ),
    ]
